### ISSUE TITLE
Is there a way to only run Google Analytics  in production environment?

### ISSUE THREAD

**Issue by mma183** [eric-wilson/angular-google-analytics-starter#1]
I tried the following in AnalyticsService, , doesn't seem work.

  public subscribe() {
    if(environment.production)
    {
      if (!this.subscription) {
        // subscribe to any router navigation and once it ends, write out the google script notices
        this.subscription = this.router.events.subscribe( e => {
          if (e instanceof NavigationEnd) {
            // this will find & use the ga function pulled via the google scripts
            try {
              ga('set', 'page', e.urlAfterRedirects);
              ga('send', 'pageview');
              console.log(`logging: ${e.urlAfterRedirects} to google analytics`);
            } catch {
               console.log('tracking not found - make sure you installed the scripts');
            }
          }
        });
      }
    }

  }

**Comment by eric-wilson** [comment]
Yes, you can turn the subscription and custom tracking off based on the production flag.

See: [commit 72389ff](https://github.com/eric-wilson/angular-google-analytics-starter/commit/72389ff8585241ee6e41ebb890519f34f375b1a9)

I just updated the code, with an example.  The main things to do, is add an import to the environment variables.  Just point to the root environment file, since the build process will inject the correct environment file when you do the build with the `--prod flag`.

For example to test it with prod you can do the following:
```bash
npm start --prod
```

without the flag
```bash
npm start
```

for the build with prod
```
ng build --prod
```
